# netlify.toml
[build]
  command = "npm run build"
  publish = "dist"

# 1) Redirect ANY /api/<splat> → https://swapi.info/api/<splat>
[[redirects]]
  from   = "/api/:splat"
  to     = "https://swapi.info/api/:splat"
  status = 200
  force  = true

# 2) Add CORS header to all those routes
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"